version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd aws-demo-sns
      - npm install

  build:
    commands:
      - echo Building Next.js app...
      - npm run build

artifacts:
  base-directory: aws-demo-sns/out
  files:
    - '**/*'
